### ISSUE TITLE
Should we provide a library?

### ISSUE THREAD

**Issue by jwass** [OvertureMaps/overturemaps-py#10]
There's an opportunity to provide a library to help download and access Overture data within Python. Currently the functionality is there mainly to support the CLI but if there is interest, we could break those parts out and support a broader API.

**Comment by Spothedog1** [comment]
I'm doing this right now, but would be pretty easy to just abstract the download function to `core.py` so I could just import that and call it a day

```
from overturemaps.core import record_batch_reader
from overturemaps.cli import get_writer, copy

def get_theme_data(theme: str, bbox: Dict[str, float], output_file: str) -> None:
    """
    Gets the theme data for a given bounding box
    """

    bbox_tuple = (bbox["xmin"], bbox["ymin"], bbox["xmax"], bbox["ymax"])
    reader = record_batch_reader(theme, bbox_tuple)

    with get_writer("geoparquet", output_file, schema=reader.schema) as writer:
        copy(reader, writer)
```

Additionally I wanted to open a PR to add the divisions types to the `type_theme_map`, would love to get added as a contributor and help out. Was there any reason you left it out on the April update?

**Comment by jwass** [comment]
@Spothedog1 The missing division types was an oversight. I realized I needed it and just committed it in 1e92f52e1bc0. But feel free to open other PRs in the future. For new functionality, definitely start an issue to discuss before writing and submitting a PR with lots of code changes.
