### ISSUE TITLE
Windows Post Installation: S3FileSystem Import error

### ISSUE THREAD

**Issue by koyo-jakanees** [OvertureMaps/overturemaps-py#38]
Hello, 
I've been hoping to try out the application for quite sometime now after attending a [QOD April talk](https://www.youtube.com/live/OJkoXgWvcNY) by @mtravis which piqued my interest on overture data,  geoparquet and cloud native geodata. Besides trying to use this tool to dev a QGIS plugin based on it.
Having followed closely the docs and Repo ReadME.

```bash
pip install overturemaps
```

The Installation step  goes through smoothly.  But when giving the cli tool a try I usually get an error as per the logs below. 

A few steps after exploring the application and obviously googling.
Decided to tinker a lil bit ```s3fs``` in place ```pyarrow.fs```   in `overmaps/core.py`  record_batch_reader. [SE thread](https://stackoverflow.com/questions/45082832/how-to-read-partitioned-parquet-files-from-s3-using-pyarrow-in-python)
And now I can actually get the parquet files.
Changes I tried in ```core.py```

```python
....
# import pyarrow.fs as fs
import s3fs as fs
```

and in ```record_batch_reader```  fn

```python

def record_batch_reader(overture_type, bbox=None) -> Optional[pa.RecordBatchReader]:
....
    dataset = ds.dataset(
        path, filesystem=fs.S3FileSystem(anon=True, cache_regions=True)
    )
```

Tested both the CLI interface and script/module interface
Not sure if it's an [OS issue](https://issues.apache.org/jira/browse/ARROW-12839)

Results when using s3fs

- QGIS
![image](https://github.com/user-attachments/assets/67342da6-e5eb-45c8-b13a-2cd6405aefae)

- lonboard as a library

Not so much  but was simply exploring on the fly
https://github.com/koyo-jakanees/demo/blob/main/overturemaps_lonboard.ipynb

Environment:
 - python 312
 - gdal 3.9.1 optional but also wanted to try geopandas example
 - OSGeo4W
 - Windows 11

sorry for the long post

Error log:

```pwsh
overturemaps download --bbox=-71.068,42.353,-71.058,42.363 -f geoparquet --type=building --output=boston.geoparquet
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\OSGeo4W\bin\apps\Python312\Scripts\overturemaps.exe\__main__.py", line 7, in <module>
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\overturemaps\cli.py", line 88, in download
    reader = record_batch_reader(type_, bbox)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\overturemaps\core.py", line 35, in record_batch_reader
    path, filesystem=fs.S3FileSystem(anonymous=True, region="us-west-2")
                     ^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\bin\apps\Python312\Lib\site-packages\pyarrow\fs.py", line 71, in __getattr__
    raise ImportError(
ImportError: The pyarrow installation is not built with support for 'S3FileSystem'
```

**Comment by mtravis** [comment]
@koyo-jakanees glad to hear you found the QOD interesting and it inspired you to find this tool.

I think your issue is your running the QGIS bundled version of python and that has a version of `pyarrow` that does not contain `pyarrow.fs` You could try setting overturemaps in a virtual environment perhaps.

On I'm also thinking of building a QGIS plugin for downloading Overture data and would be happy to work on that with you.

**Comment by koyo-jakanees** [comment]
@mtravis Thanks for the gotcha. I was using ```pyarrow<=15.0```  which come bundled with OSGeo4W installer by default. after upgrading to version 17.0 current stable version. The Overture CLI too works okay. I think pinning pyarrow>=17.0 in  the requirements should suffice. 
```pwsh
 C:\OSGeo4W\bin\bin\python.exe -m pip install -U pyarrow
```
Instead of using a virtual environment. (Just a personal pref to have geo projects on windows within OSGeo4W)

I'm trying the notebook once more and close the issue.

Edit: Both examples work fine after upgrading
