### ISSUE TITLE
Add support for bbox filtering when reading generated parquet files

### ISSUE THREAD

**Issue by songololo** [OvertureMaps/overturemaps-py#40]
When opening an `overturemaps-py` generated `geoparquet` file from `geopandas` it isn't possible to filter by bounding box:

For example, this:
```py
gpd.read_parquet(str(input_path.resolve()), bbox=bounds_buff.bounds)
```

Throws this:
```
ValueError: Specifying 'bbox' not supported for this Parquet file (it should either have a bbox covering column or use 'point' encoding).
```

It would be extremely useful if generated `geoparquet` files supported this functionality to assist with targeted `gpd.read_parquet` reads for a given `bbox`.

**Comment by songololo** [comment]
Pull request proposed for fixing this behaviour: https://github.com/OvertureMaps/overturemaps-py/pull/41

**Comment by jwass** [comment]
Closing after #41 was merged
